name: debug on comment
on:
  issue_comment:
    types: [created] # Trigger on new comments

jobs:
  validate-product-parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install npm dependencies
        run: npm install

      - name: Extract client name from comment
        id: extract-client-name
        run: |
          # Extract client name from comment body
          CLIENT_NAME=$(echo "${{ github.event.comment.body }}" | grep -oP '(?<=run parser on client).*')
          echo "::set-output name=client_name::${CLIENT_NAME}"

      - name: Run insert-client script
        run: npm run debug ${{ steps.extract-client-name.outputs.client_name }}
